---

  - name: Add the docker GPG key.
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add our APT repository.
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable

  - name: Install docker & its dependencies.
    apt: "{{ items }}"
      state: latest
      update_cache: true

      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
...