---
- hosts: all
  become: yes
  roles:
    - install_docker

- hosts: docker_swarm_init_master
  become: yes
  roles:
    - docker_swarm_init_on_master

- hosts: docker_swarm_masters
  become: yes
  roles:
    - join_swarm_as_manager

- hosts: docker_swarm_workers
  become: yes
  roles:
    - join_swarm_as_worker
...