---
- hosts: all
  become: yes
  roles:
    - install_docker

- hosts: dockerswarminitmaster
  become: yes
  roles:
    - docker_swarm_init_on_master

- hosts: dockerswarmmasters
  become: yes
  roles:
    - join_swarm_as_master

- hosts: dockerswarmworkers
  become: yes
  roles:
    - join_swarm_as_worker
...