---
- hosts: all
  become: yes
  roles:
    - install_docker

- hosts: docker-swarm-init-master
  become: yes
  roles:
    - docker_swarm_init_on_master

- hosts: docker-swarm-masters
  become: yes
  roles:
    - join_swarm_as_master

- hosts: docker-swarm-workers
  become: yes
  roles:
    - join_swarm_as_worker
...