---
- name: Copy App to Apache Owner Folder
  shell: "rsync -av {{ app_download_dest }}/app/ {{ app_dest }}"

- name: Copy Apache Config File
  template:
    src: "apache.conf"
    dest: "/etc/apache2/sites-available/000-default.conf"
  notify: restart apache