---
- hosts: lamp
  remote_user: ubuntu
  become: true  # SUDO

  tasks:
    - name: Install Packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true

      with_items:
        - apache2
        - mysql-server
        - mysql-common
        - mysql-client
        - libapache2-mod-wsgi

    - name: Start Services
      service:
        name: "{{ item }}"
        state: running
      with_items:
        - apache2
        - mysql

    - name: Shell Scripts to Enable SSL
      shell: a2enmod ssl

    - name: Enable Default HTTPS site
      shell: a2ensite default-ssl

    - name: Restart Apache
      service:
        name: apache2
        state: restarted