---
- hosts: lamp
  remote_user: ubuntu
  become: true  # SUDO

  tasks:
  - name: Install Packages
    apt:
      name: "{{ item }}"
      state: present
      update_cache: true

    with_items:
      - apache2
      - mysql-server
      - mysql-common
      - mysql-client
      - libapache2-mod-wsgi
      - python3
       - python3-pip

  - name: Start Services
    service:
      name: "{{ item }}"
      state: running
    with_items:
      - apache2
      - mysql

  - name: Shell Scripts to Enable SSL
    shell: a2enmod ssl

  - name: Enable Default HTTPS site
    shell: a2ensite default-ssl
    notify: restart apache

    # Database
  - name: Install Python MySQL Library
    apt:
      name: python-mysqldb
      state: present

  - name: Create MySQL User
  mysql_user:
    name: appuser
    password: <NOTTHEPASSWORD>
    priv: "*.*:ALL"
    state: present

  - name: Create MySQL Database
    mysql_db:
      name: appdata
      state: present

    # Install Application Code
  - name: Download App
    git:
      repo: https://github.com/whelmed/ansible_demo.git
      dest: /tmp/webapp

  - name: Install App Requirements
    pip:
      requirements: /tmp/webapp/app/requirements.txt

    # Configure Website

  - name: Copy App to Apache Owner Folder
    shell: "rsync -av /tmp/webapp/app/ /var/www/webapp"

  - name: Copy Apache Config File
    copy:
      src: "apache.conf"
      dest: "/etc/apache2/sites-available/000-default.conf"
    notify: restart apache



  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted