---

- name: "Initialise a new swarm on the master node."
  docker_swarm:
    state: present

  register: docker_swarm_info

- name: "DEBUG our docker swarm info BEFORE assigning it to a host."
  debug:
    var: docker_swarm_info

- name: "Add a host, which stores our docker_swarm_info as a variable."
  add_host:
    name: docker-swarm-info-host
    dockerinfo: docker_swarm_info
    dockerjointokenworker: docker_swarm_info.swarm_facts.JoinToken.Worker
    dockerjointokenmanager: docker_swarm_info.swarm_facts.JoinToken.Manager

- name: "DEBUG RETRIEVE the variable information from our new host"
  debug:
    var: "{{ hostvars['docker-swarm-info-host']['dockerinfo'] }}"

- name: "DEBUG RETRIEVE the worker token information from our new host"
  debug:
    var: "{{ hostvars['docker-swarm-info-host']['dockerjointokenworker']}}"

- name: "DEBUG RETRIEVE the worker token information from our new host"
  debug:
    var: "{{ hostvars['docker-swarm-info-host']['dockerjointokenmanager']}}"