---

- name: "Initialise a new swarm on the master node."
  docker_swarm:
    state: present


- name: "Retrieve the swarm join command, and save it in a global variable."
  docker_swarm_info:
  ignore_errors: yes
  register: docker_swarm_info

- name: "Add a host, which stores our docker_swarm_info as a variable."
  add_host:
    name: 'docker_swarm_info'
    docker_swarm_info: "{{ docker_swarm_info }}"