---

- name: "Initialise a new swarm on the master node."
  docker_swarm:
    state: present


- name: "Retrieve the swarm join command, and save it in a global variable."
  docker_swarm_info:
  ignore_errors: yes
  register: docker_swarm_info

- name: "DEBUG our docker swarm info BEFORE assigning it to a host."
  debug:
    var: docker_swarm_info

- name: "Add a host, which stores our docker_swarm_info as a variable."
  add_host:
    name: docker-swarm-info-host
    dockerinfo: docker_swarm_info

- name: "DEBUG RETRIEVE the variable information from our new host"
  debug:
    var: "{{ hostvars.docker-swarm-info-host.docker_swarm_info }}"