---
- name: "Add a new manager node to our swarm."
  docker_swarm:
    state: join
    join_token: "{{ docker_swarm_info.swarm_facts.JoinTokens.Manager }}"
    remote_addrs: [ '{{ groups.docker-swarm-init-master[0] }}' ]
...