---
- name: Download and install NGINX + Git
  apt:
    state: latest
    update_cache: true
    with_items: "{{ packages_to_install }}"

- name: Start our NGINX service.
  service:
    name: nginx
    state: started

- name: Update our website from a GIT repository.
  git:
    repo: "{{ git_repository }}"
    dest: "{{ install_directory }}"

- name: Install our NGINX conf file the node computer.
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  register: nginx_config

- name: Reload NGINX
  service:
    name: nginx
    state: reloaded
  when: nginx_config.changed
...