---
aws_dependencies:
  - glibc
  - groff
  - less
  - unzip
  - zipinfo

install_x86: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
install_arm: "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip"

install_directory: "~/AWS_Installer"
install_file_name: "awscliv2.zip"